language: node_js
node_js:
  - "node"
  - "7"
  - "6"
services:
  - postgresql
before_script:
  - cp .env.example .env
  - psql -c 'create database express_test;' -U postgres
  - NODE_ENV=test npm run migrate
script:
  - npm run test:coverage
after_script:
  - npm run codecov
